apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: fint-test-client
  namespace: fint-core
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`alpha.felleskomponent.no`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: fint-test-client
          namespace: fint-core
          port: 3000
